name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Overwrite the run_order.json
        run: |
          echo "$(jq -r '.[].scripts |= map(select(. != "copy_admin_scripts.sh"))' scripts/run_order.json)" > scripts/run_order.json
      - name: Run the scripts
        run: |
          sudo bash install.sh
